server:
  port: 4004

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOriginPatterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "http://20.219.107.39"
              - "http://20.219.107.39:*"
              - "https://20.219.107.39"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:http://auth-service:4005}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: ${PATIENT_SERVICE_URL:http://patient-service:4000}
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: patient-service-direct-route
          uri: ${PATIENT_SERVICE_URL:http://patient-service:4000}
          predicates:
            - Path=/patients,/patients/**
          filters:
            - JwtValidation

        - id: api-docs-patient-route
          uri: ${PATIENT_SERVICE_URL:http://patient-service:4000}
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: ${AUTH_SERVICE_URL:http://auth-service:4005}
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
